/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedDecideRouteImport } from './routes/_authenticated/decide'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as ApiPurchasePalRouteImport } from './routes/api/purchase-pal'
import { Route as ApiTrackerAssistantRouteImport } from './routes/api/tracker-assistant'
import { Route as AuthenticatedPurchasePalIndexRouteImport } from './routes/_authenticated/purchase-pal.index'
import { Route as AuthenticatedPurchasePalThreadIdRouteImport } from './routes/_authenticated/purchase-pal.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecideRoute = AuthenticatedDecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPurchasePalRoute = ApiPurchasePalRouteImport.update({
  id: '/api/purchase-pal',
  path: '/api/purchase-pal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackerAssistantRoute = ApiTrackerAssistantRouteImport.update({
  id: '/api/tracker-assistant',
  path: '/api/tracker-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPurchasePalIndexRoute =
  AuthenticatedPurchasePalIndexRouteImport.update({
    id: '/purchase-pal/',
    path: '/purchase-pal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasePalThreadIdRoute =
  AuthenticatedPurchasePalThreadIdRouteImport.update({
    id: '/purchase-pal/$threadId',
    path: '/purchase-pal/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/decide': typeof AuthenticatedDecideRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/api/purchase-pal': typeof ApiPurchasePalRoute
  '/api/tracker-assistant': typeof ApiTrackerAssistantRoute
  '/purchase-pal/$threadId': typeof AuthenticatedPurchasePalThreadIdRoute
  '/purchase-pal/': typeof AuthenticatedPurchasePalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/decide': typeof AuthenticatedDecideRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/api/purchase-pal': typeof ApiPurchasePalRoute
  '/api/tracker-assistant': typeof ApiTrackerAssistantRoute
  '/purchase-pal/$threadId': typeof AuthenticatedPurchasePalThreadIdRoute
  '/purchase-pal': typeof AuthenticatedPurchasePalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/decide': typeof AuthenticatedDecideRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/api/purchase-pal': typeof ApiPurchasePalRoute
  '/api/tracker-assistant': typeof ApiTrackerAssistantRoute
  '/_authenticated/purchase-pal/$threadId': typeof AuthenticatedPurchasePalThreadIdRoute
  '/_authenticated/purchase-pal/': typeof AuthenticatedPurchasePalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/budget'
    | '/decide'
    | '/tracker'
    | '/api/purchase-pal'
    | '/api/tracker-assistant'
    | '/purchase-pal/$threadId'
    | '/purchase-pal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/budget'
    | '/decide'
    | '/tracker'
    | '/api/purchase-pal'
    | '/api/tracker-assistant'
    | '/purchase-pal/$threadId'
    | '/purchase-pal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/app'
    | '/_authenticated/budget'
    | '/_authenticated/decide'
    | '/_authenticated/tracker'
    | '/api/purchase-pal'
    | '/api/tracker-assistant'
    | '/_authenticated/purchase-pal/$threadId'
    | '/_authenticated/purchase-pal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiPurchasePalRoute: typeof ApiPurchasePalRoute
  ApiTrackerAssistantRoute: typeof ApiTrackerAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decide': {
      id: '/_authenticated/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof AuthenticatedDecideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/purchase-pal': {
      id: '/api/purchase-pal'
      path: '/api/purchase-pal'
      fullPath: '/api/purchase-pal'
      preLoaderRoute: typeof ApiPurchasePalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tracker-assistant': {
      id: '/api/tracker-assistant'
      path: '/api/tracker-assistant'
      fullPath: '/api/tracker-assistant'
      preLoaderRoute: typeof ApiTrackerAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchase-pal/': {
      id: '/_authenticated/purchase-pal/'
      path: '/purchase-pal'
      fullPath: '/purchase-pal/'
      preLoaderRoute: typeof AuthenticatedPurchasePalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-pal/$threadId': {
      id: '/_authenticated/purchase-pal/$threadId'
      path: '/purchase-pal/$threadId'
      fullPath: '/purchase-pal/$threadId'
      preLoaderRoute: typeof AuthenticatedPurchasePalThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedDecideRoute: typeof AuthenticatedDecideRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedPurchasePalThreadIdRoute: typeof AuthenticatedPurchasePalThreadIdRoute
  AuthenticatedPurchasePalIndexRoute: typeof AuthenticatedPurchasePalIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedDecideRoute: AuthenticatedDecideRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedPurchasePalThreadIdRoute: AuthenticatedPurchasePalThreadIdRoute,
  AuthenticatedPurchasePalIndexRoute: AuthenticatedPurchasePalIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiPurchasePalRoute: ApiPurchasePalRoute,
  ApiTrackerAssistantRoute: ApiTrackerAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
